name: hexlistserver
dependencies:
- python=3.5.1
- psycopg2=2.6.1
- pip
- pip:
  - flask==0.10.1
  - Flask-SQLAlchemy==2.1
  - Flask-Migrate==1.8.0
  - gunicorn==19.4.5
  - flask-login==0.3.2
  - passlib==1.6.5
  - Flask-HTTPAuth==3.1.1
  - Flask-ErrorMail==0.2.2
  - requests==2.10.0
  - Flask-WTF==0.12
  - RandomWords==0.2.0
  - rq==0.6.0
  - beautifulsoup4==4.4.1
  - petname==1.12
