"""empty message

Revision ID: 0182513664e7
Revises: 86c760f272c1
Create Date: 2016-06-05 18:04:28.368132

"""

# revision identifiers, used by Alembic.
revision = '0182513664e7'
down_revision = '86c760f272c1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('hex_object_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_objects')
    ### end Alembic commands ###
