"""empty message

Revision ID: 12b4964ebf1e
Revises: None
Create Date: 2016-05-22 14:05:08.823001

"""

# revision identifiers, used by Alembic.
revision = '12b4964ebf1e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_objects_username'), 'user_objects', ['username'], unique=False)
    op.create_table('hex_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_object_id'], ['user_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hex_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    op.drop_table('hex_objects')
    op.drop_index(op.f('ix_user_objects_username'), table_name='user_objects')
    op.drop_table('user_objects')
    ### end Alembic commands ###
