"""empty message

Revision ID: 15b87a411f4d
Revises: ec14e81a9db6
Create Date: 2016-10-01 10:24:22.809944

"""

# revision identifiers, used by Alembic.
revision = '15b87a411f4d'
down_revision = 'ec14e81a9db6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hex_objects_image_path'), 'hex_objects', ['image_path'], unique=False)
    op.create_index(op.f('ix_hex_objects_name'), 'hex_objects', ['name'], unique=False)
    op.create_index(op.f('ix_ios_hex_locations_location'), 'ios_hex_locations', ['location'], unique=False)
    op.create_index(op.f('ix_link_objects_description'), 'link_objects', ['description'], unique=False)
    op.create_index(op.f('ix_link_objects_url'), 'link_objects', ['url'], unique=False)
    op.create_index(op.f('ix_link_objects_web_page_title'), 'link_objects', ['web_page_title'], unique=False)
    op.create_index(op.f('ix_password_resets_code'), 'password_resets', ['code'], unique=False)
    op.create_index(op.f('ix_send_objects_recipient_id'), 'send_objects', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_send_objects_sender_id'), 'send_objects', ['sender_id'], unique=False)
    op.create_index(op.f('ix_user_objects_email'), 'user_objects', ['email'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_objects_email'), table_name='user_objects')
    op.drop_index(op.f('ix_send_objects_sender_id'), table_name='send_objects')
    op.drop_index(op.f('ix_send_objects_recipient_id'), table_name='send_objects')
    op.drop_index(op.f('ix_password_resets_code'), table_name='password_resets')
    op.drop_index(op.f('ix_link_objects_web_page_title'), table_name='link_objects')
    op.drop_index(op.f('ix_link_objects_url'), table_name='link_objects')
    op.drop_index(op.f('ix_link_objects_description'), table_name='link_objects')
    op.drop_index(op.f('ix_ios_hex_locations_location'), table_name='ios_hex_locations')
    op.drop_index(op.f('ix_hex_objects_name'), table_name='hex_objects')
    op.drop_index(op.f('ix_hex_objects_image_path'), table_name='hex_objects')
    ### end Alembic commands ###
