"""empty message

Revision ID: 4c2c29343aca
Revises: b9044df16248
Create Date: 2016-04-15 11:04:09.774003

"""

# revision identifiers, used by Alembic.
revision = '4c2c29343aca'
down_revision = 'b9044df16248'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hex_objects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hex_objects', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hex_objects', type_='foreignkey')
    op.drop_column('hex_objects', 'user_id')
    ### end Alembic commands ###
