"""empty message

Revision ID: 5453a337ebda
Revises: 12b4964ebf1e
Create Date: 2016-05-22 14:05:31.340515

"""

# revision identifiers, used by Alembic.
revision = '5453a337ebda'
down_revision = '12b4964ebf1e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('hex_object_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('links')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hex_object_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], name='links_hex_object_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='links_pkey')
    )
    op.drop_table('link_objects')
    ### end Alembic commands ###
