"""empty message

Revision ID: 60c17f103996
Revises: e1753cce6c25
Create Date: 2016-07-04 16:59:25.803348

"""

# revision identifiers, used by Alembic.
revision = '60c17f103996'
down_revision = 'e1753cce6c25'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link_objects', sa.Column('web_page_title', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link_objects', 'web_page_title')
    ### end Alembic commands ###
