"""empty message

Revision ID: 623732216a1a
Revises: 15b87a411f4d
Create Date: 2016-10-01 10:35:41.702281

"""

# revision identifiers, used by Alembic.
revision = '623732216a1a'
down_revision = '15b87a411f4d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_hex_objects_owner_id'), 'hex_objects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_hex_objects_user_object_id'), 'hex_objects', ['user_object_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hex_objects_user_object_id'), table_name='hex_objects')
    op.drop_index(op.f('ix_hex_objects_owner_id'), table_name='hex_objects')
    ### end Alembic commands ###
