"""empty message

Revision ID: 660f6210cf67
Revises: 6b2b32dd1fac
Create Date: 2016-04-15 10:57:46.434638

"""

# revision identifiers, used by Alembic.
revision = '660f6210cf67'
down_revision = '6b2b32dd1fac'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
