"""empty message

Revision ID: 6b2b32dd1fac
Revises: 09b12aedc3f5
Create Date: 2016-04-15 07:16:24.909367

"""

# revision identifiers, used by Alembic.
revision = '6b2b32dd1fac'
down_revision = '09b12aedc3f5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hex_objects', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.add_column('hex_objects', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hex_objects', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'hex_objects', 'users', ['user_id'], ['id'])
    op.drop_column('hex_objects', 'owner')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hex_objects', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'hex_objects', type_='foreignkey')
    op.drop_constraint(None, 'hex_objects', type_='foreignkey')
    op.drop_column('hex_objects', 'user_id')
    op.drop_column('hex_objects', 'owner_id')
    op.drop_table('users')
    ### end Alembic commands ###
