"""empty message

Revision ID: 70e1da70565d
Revises: 3488ba510732
Create Date: 2016-04-18 23:46:06.081050

"""

# revision identifiers, used by Alembic.
revision = '70e1da70565d'
down_revision = '3488ba510732'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_objects', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('user_objects', sa.Column('username', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_objects_username'), 'user_objects', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_objects_username'), table_name='user_objects')
    op.drop_column('user_objects', 'username')
    op.drop_column('user_objects', 'password_hash')
    ### end Alembic commands ###
