"""empty message

Revision ID: 77792d0403d4
Revises: 9105c7d0d8ab
Create Date: 2016-06-11 16:15:07.627766

"""

# revision identifiers, used by Alembic.
revision = '77792d0403d4'
down_revision = '9105c7d0d8ab'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ios_hex_locations')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ios_hex_locations',
    sa.Column('hex_object_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], name='ios_hex_locations_hex_object_id_fkey'),
    sa.PrimaryKeyConstraint('hex_object_id', name='ios_hex_locations_pkey')
    )
    ### end Alembic commands ###
