"""empty message

Revision ID: 79bb7e2b9748
Revises: dcbf3a9eb09e
Create Date: 2016-08-06 18:22:33.798169

"""

# revision identifiers, used by Alembic.
revision = '79bb7e2b9748'
down_revision = 'dcbf3a9eb09e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ios_hex_locations_hex_object_id_fkey', 'ios_hex_locations', type_='foreignkey')
    op.drop_constraint('ios_hex_locations_user_object_id_fkey', 'ios_hex_locations', type_='foreignkey')
    op.create_foreign_key(None, 'ios_hex_locations', 'user_objects', ['user_object_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ios_hex_locations', 'hex_objects', ['hex_object_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('link_objects_hex_object_id_fkey', 'link_objects', type_='foreignkey')
    op.create_foreign_key(None, 'link_objects', 'hex_objects', ['hex_object_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('send_objects_hex_object_id_fkey', 'send_objects', type_='foreignkey')
    op.create_foreign_key(None, 'send_objects', 'hex_objects', ['hex_object_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'send_objects', type_='foreignkey')
    op.create_foreign_key('send_objects_hex_object_id_fkey', 'send_objects', 'hex_objects', ['hex_object_id'], ['id'])
    op.drop_constraint(None, 'link_objects', type_='foreignkey')
    op.create_foreign_key('link_objects_hex_object_id_fkey', 'link_objects', 'hex_objects', ['hex_object_id'], ['id'])
    op.drop_constraint(None, 'ios_hex_locations', type_='foreignkey')
    op.drop_constraint(None, 'ios_hex_locations', type_='foreignkey')
    op.create_foreign_key('ios_hex_locations_user_object_id_fkey', 'ios_hex_locations', 'user_objects', ['user_object_id'], ['id'])
    op.create_foreign_key('ios_hex_locations_hex_object_id_fkey', 'ios_hex_locations', 'hex_objects', ['hex_object_id'], ['id'])
    ### end Alembic commands ###
