"""empty message

Revision ID: 7e6520f5b341
Revises: c5f53626cbee
Create Date: 2016-04-10 23:24:23.510520

"""

# revision identifiers, used by Alembic.
revision = '7e6520f5b341'
down_revision = 'c5f53626cbee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hex_links', sa.Column('hex_object_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'hex_links', 'hex_objects', ['hex_object_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hex_links', type_='foreignkey')
    op.drop_column('hex_links', 'hex_object_id')
    ### end Alembic commands ###
