"""empty message

Revision ID: 86c760f272c1
Revises: c93648f20c64
Create Date: 2016-06-05 17:51:56.928349

"""

# revision identifiers, used by Alembic.
revision = '86c760f272c1'
down_revision = 'c93648f20c64'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_objects')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_objects',
    sa.Column('sender_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('recipient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hex_object_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], name='send_objects_hex_object_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hex_object_id', name='send_objects_pkey')
    )
    ### end Alembic commands ###
