"""empty message

Revision ID: 9ccd060f9c7e
Revises: 79bb7e2b9748
Create Date: 2016-08-17 22:16:21.767949

"""

# revision identifiers, used by Alembic.
revision = '9ccd060f9c7e'
down_revision = '79bb7e2b9748'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.String(), nullable=True),
    sa.Column('user_object_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_object_id'], ['user_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_resets')
    ### end Alembic commands ###
