"""empty message

Revision ID: b9044df16248
Revises: 660f6210cf67
Create Date: 2016-04-15 10:59:27.736386

"""

# revision identifiers, used by Alembic.
revision = 'b9044df16248'
down_revision = '660f6210cf67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('hex_objects_user_id_fkey', 'hex_objects', type_='foreignkey')
    op.drop_column('hex_objects', 'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hex_objects', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('hex_objects_user_id_fkey', 'hex_objects', 'users', ['user_id'], ['id'])
    ### end Alembic commands ###
