"""empty message

Revision ID: cde00db71228
Revises: c1c25828340e
Create Date: 2016-05-30 18:43:25.727131

"""

# revision identifiers, used by Alembic.
revision = 'cde00db71228'
down_revision = 'c1c25828340e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('send_objects',
    sa.Column('sender_id', sa.String(), nullable=True),
    sa.Column('recipient_id', sa.String(), nullable=True),
    sa.Column('hex_object_id', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hex_object_id'], ['hex_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hex_object_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('send_objects')
    ### end Alembic commands ###
