"""empty message

Revision ID: e949ef84eb6b
Revises: 9ccd060f9c7e
Create Date: 2016-08-17 23:18:56.800824

"""

# revision identifiers, used by Alembic.
revision = 'e949ef84eb6b'
down_revision = '9ccd060f9c7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('password_resets', 'code')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password_resets', sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
