"""empty message

Revision ID: ec14e81a9db6
Revises: 9ccd060f9c7e
Create Date: 2016-09-11 22:28:37.901748

"""

# revision identifiers, used by Alembic.
revision = 'ec14e81a9db6'
down_revision = '9ccd060f9c7e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hex_objects', sa.Column('is_private', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hex_objects', 'is_private')
    ### end Alembic commands ###
